[build]
  command = "next build"
  publish = ".next"

[[redirects]]
  from = "/index.php"
  to = "/"
  status = 301

[[redirects]]
  from = "/about.php"
  to = "/about"
  status = 301

[[redirects]]
  from = "/found-a-bird.php"
  to = "/found-a-bird"
  status = 301

[[redirects]]
  from = "/how-to-help.php"
  to = "/how-to-help"
  status = 301

[[redirects]]
  from = "/in-the-news.php"
  to = "/"
  status = 301

[[redirects]]
  from = "/educational-birds.php"
  to = "/"
  status = 301

[[redirects]]
  from = "/photo-gallery.php"
  to = "/"
  status = 301
